detection:
  model  : "yolov8"
  weight : "weights/yolov8l_crowdhuman-human-only_50e_1024.pt"
  imgsz  : [768,1280]
  conf   : 0.65
  classes: [0,]
  verbose: False
  device : "cuda"
  kwargs : None 

annotation: 
  active: False
  save  : False
  show  : False
  print : False

paths: 
  root_dir  : ${oc.env:PROJECT_ROOT}
  log_dir   : ${paths.root_dir}/logs
